# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master-windows

pool:
  vmImage: 'windows-latest'

#NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages - not working, there is no such folder
#NUGET_PACKAGES: '~/.nuget/packages' - not working at restore
variables:
  buildConfiguration: 'Release'
  buildDirectory: '$(Build.SourcesDirectory)'
  NUGET_PACKAGES: '/home/vsts/.nuget/packages'

steps:
- task: Cache@2
  inputs:
    key: 'nuget | "$(Agent.OS)" | PipelineCaching/packages.lock.json'
    restoreKeys: |
       nuget | "$(Agent.OS)"
       nuget
    path: $(NUGET_PACKAGES)
    cacheHitVar: CACHE_RESTORED
  displayName: Cache NuGet packages

- script: dotnet restore
  displayName: 'dotnet restore'
  condition: ne(variables.CACHE_RESTORED, 'true')
  workingDirectory: $(buildDirectory)

- script: printenv

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
      
      Get-ChildItem '~/.nuget/packages'
    pwsh: true

- script: dir
  enabled: false
  workingDirectory: $(Pipeline.Workspace)/.nuget/packages

- task: CopyFiles@2
  displayName: Copy packages.lock.json file
  enabled: false
  inputs:
    sourceFolder: $(buildDirectory)/PipelineCaching
    contents: packages.lock.json
    targetFolder:  $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: Publish packages.lock.json file
  enabled: false
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: LockedJson

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: $(buildDirectory)
  
